CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "account_emailconfirmation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "sent" datetime NULL, "key" varchar(64) NOT NULL UNIQUE, "email_address_id" integer NOT NULL REFERENCES "account_emailaddress" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "account_emailconfirmation_email_address_id_5b7f8c58" ON "account_emailconfirmation" ("email_address_id");
CREATE TABLE IF NOT EXISTS "account_emailaddress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "verified" bool NOT NULL, "primary" bool NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "email" varchar(254) NOT NULL UNIQUE);
CREATE INDEX "account_emailaddress_user_id_2c513194" ON "account_emailaddress" ("user_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "last_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "core_address" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "street_address" varchar(100) NOT NULL, "apartment_address" varchar(100) NOT NULL, "country" varchar(2) NOT NULL, "zip" varchar(100) NOT NULL, "address_type" varchar(1) NOT NULL, "default" bool NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_coupon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(15) NOT NULL, "amount" real NOT NULL);
CREATE TABLE IF NOT EXISTS "core_refund" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "reason" text NOT NULL, "accepted" bool NOT NULL, "email" varchar(254) NOT NULL, "order_id" integer NOT NULL REFERENCES "core_order" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_payment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "stripe_charge_id" varchar(50) NOT NULL, "amount" real NOT NULL, "timestamp" datetime NOT NULL, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_order_items" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "order_id" integer NOT NULL REFERENCES "core_order" ("id") DEFERRABLE INITIALLY DEFERRED, "orderitem_id" integer NOT NULL REFERENCES "core_orderitem" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "core_address_user_id_7681a39c" ON "core_address" ("user_id");
CREATE INDEX "core_refund_order_id_7fe621fa" ON "core_refund" ("order_id");
CREATE INDEX "core_payment_user_id_274e164a" ON "core_payment" ("user_id");
CREATE UNIQUE INDEX "core_order_items_order_id_orderitem_id_f9cea05f_uniq" ON "core_order_items" ("order_id", "orderitem_id");
CREATE INDEX "core_order_items_order_id_c5dde6c1" ON "core_order_items" ("order_id");
CREATE INDEX "core_order_items_orderitem_id_e44f86b6" ON "core_order_items" ("orderitem_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "django_site" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "domain" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "socialaccount_socialapp_sites" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "socialapp_id" integer NOT NULL REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED, "site_id" integer NOT NULL REFERENCES "django_site" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "socialaccount_socialtoken" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "token" text NOT NULL, "token_secret" text NOT NULL, "expires_at" datetime NULL, "account_id" integer NOT NULL REFERENCES "socialaccount_socialaccount" ("id") DEFERRABLE INITIALLY DEFERRED, "app_id" integer NOT NULL REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq" ON "socialaccount_socialtoken" ("app_id", "account_id");
CREATE UNIQUE INDEX "socialaccount_socialapp_sites_socialapp_id_site_id_71a9a768_uniq" ON "socialaccount_socialapp_sites" ("socialapp_id", "site_id");
CREATE INDEX "socialaccount_socialapp_sites_socialapp_id_97fb6e7d" ON "socialaccount_socialapp_sites" ("socialapp_id");
CREATE INDEX "socialaccount_socialapp_sites_site_id_2579dee5" ON "socialaccount_socialapp_sites" ("site_id");
CREATE INDEX "socialaccount_socialtoken_account_id_951f210e" ON "socialaccount_socialtoken" ("account_id");
CREATE INDEX "socialaccount_socialtoken_app_id_636a42d7" ON "socialaccount_socialtoken" ("app_id");
CREATE TABLE IF NOT EXISTS "socialaccount_socialapp" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "provider" varchar(30) NOT NULL, "name" varchar(40) NOT NULL, "client_id" varchar(191) NOT NULL, "key" varchar(191) NOT NULL, "secret" varchar(191) NOT NULL);
CREATE TABLE IF NOT EXISTS "socialaccount_socialaccount" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "provider" varchar(30) NOT NULL, "uid" varchar(191) NOT NULL, "last_login" datetime NOT NULL, "date_joined" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "extra_data" text NOT NULL);
CREATE UNIQUE INDEX "socialaccount_socialaccount_provider_uid_fc810c6e_uniq" ON "socialaccount_socialaccount" ("provider", "uid");
CREATE INDEX "socialaccount_socialaccount_user_id_8146e70c" ON "socialaccount_socialaccount" ("user_id");
CREATE TABLE IF NOT EXISTS "core_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "start_date" datetime NOT NULL, "ordered_date" datetime NOT NULL, "ordered" bool NOT NULL, "being_delivered" bool NOT NULL, "received" bool NOT NULL, "refund_requested" bool NOT NULL, "refund_granted" bool NOT NULL, "billing_address_id" integer NULL REFERENCES "core_address" ("id") DEFERRABLE INITIALLY DEFERRED, "coupon_id" integer NULL REFERENCES "core_coupon" ("id") DEFERRABLE INITIALLY DEFERRED, "payment_id" integer NULL REFERENCES "core_payment" ("id") DEFERRABLE INITIALLY DEFERRED, "shipping_address_id" integer NULL REFERENCES "core_address" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "ref_code" varchar(20) NULL);
CREATE INDEX "core_order_billing_address_id_b33cde99" ON "core_order" ("billing_address_id");
CREATE INDEX "core_order_coupon_id_bade53ba" ON "core_order" ("coupon_id");
CREATE INDEX "core_order_payment_id_e5a26a3c" ON "core_order" ("payment_id");
CREATE INDEX "core_order_shipping_address_id_8c054f15" ON "core_order" ("shipping_address_id");
CREATE INDEX "core_order_user_id_b03bbffd" ON "core_order" ("user_id");
CREATE TABLE IF NOT EXISTS "core_userprofile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "stripe_customer_id" varchar(50) NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "one_click_purchasing" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "core_orderitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ordered" bool NOT NULL, "quantity" integer NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "item_id" integer NOT NULL REFERENCES "core_doctor" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "core_orderitem_user_id_323fe695" ON "core_orderitem" ("user_id");
CREATE INDEX "core_orderitem_item_id_3b7d0c2e" ON "core_orderitem" ("item_id");
CREATE TABLE IF NOT EXISTS "core_doctor_specialties" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "doctor_id" integer NOT NULL REFERENCES "core_doctor" ("id") DEFERRABLE INITIALLY DEFERRED, "specialty_id" integer NOT NULL REFERENCES "core_specialty" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "core_doctor_specialties_doctor_id_specialty_id_014d19e9_uniq" ON "core_doctor_specialties" ("doctor_id", "specialty_id");
CREATE INDEX "core_doctor_specialties_doctor_id_8d340adc" ON "core_doctor_specialties" ("doctor_id");
CREATE INDEX "core_doctor_specialties_specialty_id_05ff3989" ON "core_doctor_specialties" ("specialty_id");
CREATE TABLE IF NOT EXISTS "core_specialty" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "slug" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "core_doctor" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "price" real NOT NULL, "discount_price" real NULL, "slug" varchar(50) NOT NULL, "description" text NOT NULL, "image" varchar(100) NOT NULL, "label" varchar(1) NOT NULL);
CREATE INDEX "core_doctor_slug_592543cf" ON "core_doctor" ("slug");
CREATE TABLE IF NOT EXISTS "core_booking" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "booked_date" datetime NOT NULL, "payment_date" datetime NULL, "examination_date" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "total" real NOT NULL, "doctor_id" integer NOT NULL REFERENCES "core_doctor" ("id") DEFERRABLE INITIALLY DEFERRED, "address" varchar(500) NOT NULL);
CREATE INDEX "core_booking_user_id_55d9bfa8" ON "core_booking" ("user_id");
CREATE INDEX "core_booking_doctor_id_b089a093" ON "core_booking" ("doctor_id");
