# Generated by Django 2.2.14 on 2022-12-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Doctor',
        ),
    ]
