# Generated by Django 2.2.14 on 2022-12-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221208_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='title',
            new_name='name',
        ),
    ]
