# Generated by Django 2.2.14 on 2022-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_specialty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
