# Generated by Django 2.2.14 on 2022-12-11 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20221208_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='label',
            field=models.CharField(choices=[('P', 'danger'), ('S', 'secondary'), ('D', 'primary')], max_length=1),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(default=None, null=True)),
                ('examination_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
