# Generated by Django 2.2.14 on 2022-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221211_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
