# Generated by Django 2.2.14 on 2022-12-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_date',
            new_name='booked_date',
        ),
    ]
