# Generated by Django 2.2.14 on 2022-12-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221211_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Doctor'),
            preserve_default=False,
        ),
    ]
