# Generated by Django 2.2.14 on 2022-12-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_booking_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
