# Generated by Django 2.2.14 on 2022-12-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='discount_price',
        ),
    ]
